{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Different types of Exception Handling\n",
    "\n",
    "In Python, exception handling is used to handle errors and exceptions that occur during the execution of a program. It allows us to gracefully handle errors and prevent the program from crashing. \n",
    "\n",
    "In some there is only one logical line of code in the try block then we simply use the except block to catch the exception. \n",
    "\n",
    "But in some cases, We need the different types of exception handling to handle different types of exceptions. Here are the different types of exception handling:\n",
    "\n",
    "1. **Simple Exception Handling**: This is the most basic type of exception handling. It is used to handle all types of exceptions. It is used when we don't know what type of exception will occur.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except:\n",
    "    # code to handle the exception\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except:\n",
    "    print(\"An error occurred\")\n",
    "```\n",
    "\n",
    "In this example, we have only one logical line of code in the try block. This line of code will raise an exception because we are trying to divide a number by zero. The except block will catch the exception and print the message \"An error occurred\".\n",
    "\n",
    "\n",
    "2. **Specific Exception Handling**: This type of exception handling is used to handle a specific type of exception. It is used when we know what type of exception will occur.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except ExceptionType:\n",
    "    # code to handle the exception\n",
    "```\n",
    "\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by zero\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, we are handling the `ZeroDivisionError` exception. If this exception occurs, the message \"Cannot divide by zero\" will be printed.\n",
    "\n",
    "\n",
    "3. **Multiple Exception Handling**: This type of exception handling is used to handle multiple exceptions. It is used when we want to handle different types of exceptions in different ways.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except Exception1:\n",
    "    # code to handle Exception1\n",
    "except Exception2:\n",
    "    # code to handle Exception2\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by zero\")\n",
    "except NameError:\n",
    "    print(\"Variable is not defined\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, we are handling two exceptions: `ZeroDivisionError` and `NameError`. If `ZeroDivisionError` occurs, the message \"Cannot divide by zero\" will be printed. If `NameError` occurs, the message \"Variable is not defined\" will be printed. \n",
    "\n",
    "\n",
    "4. **Generic Exception Handling**: This type of exception handling is used to handle all exceptions except the ones that are handled specifically. It is used when we want to handle all exceptions in a generic way and handle specific exceptions separately.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except ExceptionType1:\n",
    "    # code to handle ExceptionType1\n",
    "except ExceptionType2:\n",
    "    # code to handle ExceptionType2\n",
    "except:\n",
    "    # code to handle all other exceptions\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by zero\")\n",
    "except NameError:\n",
    "    print(\"Variable is not defined\")\n",
    "except:\n",
    "    print(\"An error occurred\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, we are handling two exceptions: `ZeroDivisionError` and `NameError` specifically. If `ZeroDivisionError` occurs, the message \"Cannot divide by zero\" will be printed. If `NameError` occurs, the message \"Variable is not defined\" will be printed. For all other exceptions, the message \"An error occurred\" will be printed.\n",
    "\n",
    "\n",
    "5. **Else Block**: This block is executed if no exceptions are raised in the try block. \n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except ExceptionType:\n",
    "    # code to handle the exception\n",
    "else:\n",
    "    # code to execute if no exceptions are raised\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 1\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by zero\")\n",
    "else:\n",
    "    print(\"No exceptions occurred\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, the code in the `else` block will be executed because no exceptions were raised in the `try` block. The message \"No exceptions occurred\" will be printed.\n",
    "\n",
    "\n",
    "6. **Finally Block**: This block is always executed whether an exception is raised or not. It is used to clean up resources or perform cleanup actions.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except ExceptionType:\n",
    "    # code to handle the exception\n",
    "finally:\n",
    "    # code to execute whether an exception is raised or not\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "try:\n",
    "    x = 1 / 0\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by zero\")\n",
    "finally:\n",
    "    print(\"Finally block executed\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, the code in the `finally` block will be executed whether an exception is raised or not. The message \"Finally block executed\" will be printed. \n",
    "\n",
    "\n",
    "\n",
    "7. **Raising Exceptions**: This is used to raise exceptions manually. It is used when we want to raise an exception based on certain conditions.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "raise ExceptionType(\"Error message\")\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "x = -1\n",
    "if x < 0:\n",
    "    raise ValueError(\"Number cannot be negative\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, we are raising a `ValueError` exception with the message \"Number cannot be negative\" if the value of `x` is negative.\n",
    "\n",
    "\n",
    "\n",
    "8. **Custom Exceptions**: This is used to create custom exceptions. It is used when we want to define our own exceptions.\n",
    "\n",
    "Syntax:\n",
    "```python\n",
    "class CustomException(Exception):\n",
    "    pass\n",
    "```\n",
    "\n",
    "Example:\n",
    "```python\n",
    "class CustomException(Exception):\n",
    "    pass\n",
    "\n",
    "x = -1\n",
    "if x < 0:\n",
    "    raise CustomException(\"Number cannot be negative\")\n",
    "```\n",
    "\n",
    "Explanation:\n",
    "- In this example, we are creating a custom exception `CustomException` and raising it with the message \"Number cannot be negative\" if the value of `x` is negative.\n",
    "\n",
    "\n",
    "\n",
    "These are the different types of exception handling in Python. They are used to handle exceptions in different ways based on the requirements of the program.\n",
    "\n",
    "\n",
    "\n",
    "Let's see an example of each type of exception handling in the following code snippets.\n",
    "\n",
    "**Exercises**: \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File not found\n"
     ]
    }
   ],
   "source": [
    "## Simple exception handling in python using try and except block : \n",
    "\n",
    "# Q) Writing one logic which may throw an exception and handling that exception using try and except block.\n",
    "\n",
    "\n",
    "try:           # Try block is used to execute the code which may throw an exception\n",
    "    with open('files/sample3.json','r') as f:     # Opening a file in read mode \n",
    "        print(f.read())               # Reading the content of the file\n",
    "\n",
    "except:\n",
    "    print('File not found')   # If the file is not found then this block will be executed \n",
    "\n",
    "\n",
    "## Explanation of the above code :\n",
    "\n",
    "# In the above code we are trying to open a file in read mode using the with open statement.\n",
    "# If the file is found then the content of the file will be printed on the console.\n",
    "\n",
    "# If the file is not found then the except block will be executed and the message 'File not found' will be printed on the console.\n",
    "\n",
    "# In this simple exception handling we are not specifying the type of exception that may occur.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello, World!\n",
      "variable not defined\n"
     ]
    }
   ],
   "source": [
    "##  Exception handling with multiple except blocks :\n",
    "\n",
    "# When we are working in project we write different different logics and sometimes we may get some exceptions.\n",
    "\n",
    "try:\n",
    "    with open(\"files/sample.json\",\"r\") as f:\n",
    "        print(f.read())\n",
    "\n",
    "        a=4\n",
    "        b=5\n",
    "        print(a+m)\n",
    "\n",
    "        L=[1,2,3,4,5,6,7,8,9]\n",
    "        L[11]\n",
    "\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(\"File not found\")\n",
    "\n",
    "except NameError:\n",
    "    print(\"variable not defined\")\n",
    "\n",
    "except IndexError:\n",
    "    print(\"Index out of range\")\n",
    "\n",
    "\n",
    "## Explanation of the above code :\n",
    "\n",
    "# In the above code we are trying to open a file in read mode using the with open statement.\n",
    "# If the file is found then the content of the file will be printed on the console. \n",
    "# Then we are trying to print the value of a variable which is not defined and then we are trying to access the element of the list which is out of range.\n",
    "\n",
    "# If the file is not found then the except block will be executed and the message 'File not found' will be printed on the console.\n",
    "\n",
    "# If the variable is not defined then the except block will be executed and the message 'variable not defined' will be printed on the console.\n",
    "\n",
    "# If the index is out of range then the except block will be executed and the message 'Index out of range' will be printed on the console.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello, World!\n",
      "list index out of range\n"
     ]
    }
   ],
   "source": [
    "## Using \"except Exception as e:\" block :\n",
    "\n",
    "## Q) If we want to automatically detect the type of exception that may occur then\n",
    "    # we have to use \"except Exception as e:\"\" block ? \n",
    "\n",
    "# =>\n",
    "    # In this block the type of exception will be stored in the variable \"e\" and\n",
    "    # we can print that exception using print(e) statement in the except block.\n",
    "    # This will help us to know the type of exception that may occur in the code.\n",
    "    # This is very useful when we are working in a project and we want to know the type of exception that may occur in the code.\n",
    "\n",
    "try:\n",
    "    with open(\"files/sample.json\",\"r\") as f:\n",
    "        print(f.read())\n",
    "\n",
    "        # a=4\n",
    "        # b=5\n",
    "        # print(a+m)\n",
    "\n",
    "        L=[1,2,3,4,5,6,7,8,9]\n",
    "        L[11]\n",
    "\n",
    "        0/\"K\"\n",
    "\n",
    "\n",
    "except Exception as e:  # This block will automatically detect the type of exception that may occur in the code and store it in the variable \"e\" and then we can print that exception using print(e) statement.\n",
    "    print(e)    # This will print the type of exception that may occur in the code.\n",
    "\n",
    "\n",
    "## Explanation of the above code :\n",
    "\n",
    "# In the above code we are trying to open a file in read mode using the with open statement.\n",
    "# If the file is found then the content of the file will be printed on the console.\n",
    "# Then we are trying to print the value of a variable which is not defined and then we are trying to access the element of the list which is out of range.\n",
    "\n",
    "# If the file is not found then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If the variable is not defined then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If the index is out of range then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If we are trying to divide a number by zero then the except block will be executed\n",
    "\n",
    "## In this way we can automatically detect the type of exception that may occur \n",
    "    # in the code using \"except Exception as e:\" block.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Q) What is the difference between \"except\" and \"except Exception as e:\" block ?\n",
    "\n",
    "=>\n",
    "- In the \"except\" block we are not specifying the type of exception that may occur in the code.\n",
    "\n",
    "- In the \"except Exception as e:\" block we are specifying the type of exception that may occur in the code.\n",
    "\n",
    "- In the \"except Exception as e:\" block the type of exception will be stored in the variable \"e\" and we can print that exception using print(e) statement in the except block.\n",
    "\n",
    "- This will help us to know the type of exception that may occur in the code.\n",
    "\n",
    "- This is very useful when we are working in a project and we want to know the type of exception that may occur in the code.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello, World!\n",
      "<built-in method with_traceback of IndexError object at 0x10b3b70a0>\n"
     ]
    }
   ],
   "source": [
    "## Using \"e.with_traceback()\" method :\n",
    "\n",
    "## Let's say we not sure about error and we want to know , what kinds of error actually \n",
    "    # it may give us. \n",
    "\n",
    "# => In this case we can simply trace the error with \"e.with_traceback()\" method.\n",
    "\n",
    "try:\n",
    "    with open('files/sample.json','r') as f:\n",
    "        print(f.read())\n",
    "\n",
    "        # a = 4\n",
    "        # b = 4\n",
    "        # print(a+m)\n",
    "\n",
    "        L=[1,2,3,4,5,6,7,8,9]\n",
    "        L[100]\n",
    "\n",
    "        # 0/\"K\"\n",
    "\n",
    "except Exception as e:    # This block will automatically detect the type of exception that may occur in the code and store it in the variable \"e\" and then we can print that exception using print(e) statement.\n",
    "    print(e.with_traceback)\n",
    "\n",
    "\n",
    "## Explanation of the above code :\n",
    "\n",
    "# In the above code we are trying to open a file in read mode using the with open statement.\n",
    "# If the file is found then the content of the file will be printed on the console.\n",
    "# Then we are trying to print the value of a variable which is not defined and then we are trying to access the element of the list which is out of range.\n",
    "\n",
    "# If the file is not found then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If the variable is not defined then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If the index is out of range then the except block will be executed and the type of exception will be printed on the console.\n",
    "\n",
    "# If we are trying to divide a number by zero then the except block will be executed\n",
    "\n",
    "## In this way we can trace the error with \"e.with_traceback()\" method.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
